### ISSUE TITLE
L1-medial skeleton implementation

### ISSUE THREAD

**Issue by blukaz** [meyerls/PC-Skeletor#1]
Hi @meyerls,

thank you very much for your efforts!
I wanted to ask how far you got with the L1-medial skeleton implementation. Do you need any help?

**Comment by meyerls** [comment]
Hi @blukaz,

thanks for your interest! 
To be honest, I did not start implementing the L1-Medial algorithm since the Laplacian Contractions works fine for my case. Realistically, I will look at the L! implementation in the middle of this year. 

Do you have some knowledge or even an implementation for the algorithm? Unfortunately, I have not found any working repository except this one  - `[l1skeleton_py](https://github.com/SmartPolarBear/l1skeleton_py)` . But seems to be very slow on large point clouds.

**Comment by meyerls** [comment]
Update: in v1.0.0 we remove the l1 medial algorithm from the readme. But currently, we are implementing l1 medial skeleton (release around Oct/Nov 2023) and getting into Point2Skeleton (release around Oct/Nov 2023).
